#!/bin/bash

function do_loudly() {
    echo "+ $*"
    $*
}

set -e

SDK_INCLUDE=tinysys_c_sdk/SDK
# TODO: Move this into build.rs
SDK_H="src/include/sdk.h"
echo "+ Generating $SDK_H"
echo "// **NOTE**"  > $SDK_H
echo "// This file is autogenerated to include all of the headers from the tinysys SDK." \
                    >> $SDK_H
echo "// See \`update_rs.sh\` for details" \
                    >> $SDK_H
echo "//"           >> $SDK_H
echo                >> $SDK_H
for file in $(find $SDK_INCLUDE -type f -name "*.h" | sort); do
    if [[ -f "$file" ]]; then
        echo "#include <$(basename $file)>" >> $SDK_H
    fi
done
echo "+ Done"

# do_loudly bindgen                   \
#         src/include/wrapper.h       \
#     -o  src/sdk.rs                  \
#     --use-core                      \
#     --                              \
#     -I $SDK_INCLUDE                 \
#     --std=c++17

# Our build script generates the rs files
export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=$(riscv64-unknown-elf-gcc -print-sysroot)"
do_loudly cargo build --features=bindgen $*
do_loudly cargo fmt
