// **NOTE**
// This file is autogenerated to include all of the headers from the tinysys SDK.
// See `update_rs.sh` for details
//

#include <apu.h>
#include <basesystem.h>
#include <core.h>
#include <elf.h>
#include <encoding.h>
#include <joystick.h>
#include <keyboard.h>
#include <keyringbuffer.h>
#include <leds.h>
#include <mini-printf.h>
#include <mini-scanf.h>
#include <sdcard.h>
#include <serialinringbuffer.h>
#include <task.h>
#include <tbm_printf.h>
#include <uart.h>
#include <usbcommon.h>
#include <vpu.h>
